[package]
name = "sicknes"
version = "0.1.0"
authors = ["Stephan König <tb@octoplex.org>"]
edition = "2018"

[dependencies]
piston = "0.52.0"
piston_window = "0.111.0"
clap = "3.0.0-beta.1"
bitflags = "1.2.1"
